services:
  user-db:
    image: postgres:16
    container_name: user-db
    environment:
      POSTGRES_DB: user_db
      POSTGRES_USER: user_user
      POSTGRES_PASSWORD: user_pass
    ports:
      - "5435:5432"
    volumes:
      - user_db_data:/var/lib/postgresql/data

  user-service:
    build:
      context: .
    container_name: user-service
    depends_on:
      - user-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://user-db:5432/user_db
      SPRING_DATASOURCE_USERNAME: user_user
      SPRING_DATASOURCE_PASSWORD: user_pass
    ports:
      - "8083:8083"

volumes:
  user_db_data:
