spring:
  application:
    name: user-service

  datasource:
    url: jdbc:postgresql://localhost:5435/user_db
    username: user_user
    password: user_pass
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: user-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.example.user_service.kafka.event"
        spring.json.value.default.type: "com.example.user_service.kafka.event.UserCreatedEvent"
        spring.json.use.type.headers: false

server:
  port: 8083

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.hibernate.SQL: DEBUG
